### ISSUE TITLE
Not compatible version

### ISSUE THREAD

**Issue by vnzhlv-zh** [mabasic/ulauncher-laravel#1]
Ulauncher v4.4.0.r1 gives me this error: 

> Unexpected API error. GithubExtensionError: This extension is not compatible with current version Ulauncher extension API (v1.0.0)

**Comment by mabasic** [comment]
Yes, the extension currently only supports Ulauncher v5 (API v2.0.0).

I will dedicate some time to this, to make it work on Ulauncher v4.

**Comment by mabasic** [comment]
Read this: https://blog.laravelista.hr/2019/09/26/abandoned-laravel-extension

I'm putting this extension on hold.

**Comment by vnzhlv-zh** [comment]
> Read this: https://blog.laravelista.hr/2019/09/26/abandoned-laravel-extension
> 
> I'm putting this extension on hold.

`https://laravel.com/api/__VERSION__/search.html?search=%s` to use API docs

**Comment by mabasic** [comment]
Nice. Going to keep it for reference
