### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by KuenzelIT** [mabasic/ulauncher-laravel#2]
Hi,

do I have to know the slugs of the doc pages I want to see? Can we integrate the search of laravel docs into the extension?

Thank you!

**Comment by mabasic** [comment]
Currently you have to know the slugs of the doc pages. My intention was always to have some sort of full text search of the entire documentation.I have seen an alfred extension implement algolia search for this task...Since I'm not actively using this extension anymore, I am open to a PR.

**Comment by mabasic** [comment]
Implemented in #3
